name: Daily Rules Merge

on:
  schedule:
    - cron: "0 3,15 * * *"  
  workflow_dispatch:     

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Merge rules
      run: python merge.py

    - name: 提交更改
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add rules.txt
        if git diff-index --quiet HEAD; then
          echo "No changes"
        else
          git commit -m "Auto-update: Merged rules $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
        
    - name: Validate rules format
      run: |
        # 检查文件是否以有效注释开头
        head -n 10 rules.txt | grep -q '! Merged AdBlock Rules'
        # 检查首条规则类型
        head -n 11 rules.txt | tail -n 1 | grep -qE '^@@|^\|\||^\/'
        echo "Rules format validation passed"
